### ISSUE TITLE
Make changes on the project

### ISSUE THREAD

**Issue by abuthahir-19** [abuthahir-19/Learn_Github#1]
@Sne-har-shini @shalini-2201 @joemariam17 @Sneha-15-2001. Learn web Development by making projects fetch all the files in this repository by using the git command "git pull" to get all the files to your local repository after create a new branch of your name (eg. sneha) and upload your modified project to that branch and don't merge that branch to the main branch just keep your changes in your branch

**Comment by abuthahir-19** [comment]
I want anyone to close this issue I have created after replying to this message. Thank U

**Comment by shalini-2201** [comment]
done

**Comment by abuthahir-19** [comment]
ok shalini
